[project]
name = "puppy-plugin"
version = "0.1.0"
description = "SillyTavern小狗截图美化插件"
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pillow>=10.0.0",
    "numpy>=1.24.0",
    "colorsys",
]